<?php

return [
    'COLLEGE_CODE' => env('COLLEGE_CODE'),
    'COLLEGE_NAME' => env('COLLEGE_NAME'),

    'COLLEGE_NAME_KURDISH' => env('COLLEGE_NAME_KURDISH'),

    'STUDENT_NUMBER_PREFIX' => env('STUDENT_NUMBER_PREFIX'),

    'HELP_EMAIL' => env('HELP_EMAIL'),

    'SUPPORT_PRIMARY_PHONE_NUMBER' => env('SUPPORT_PRIMARY_PHONE_NUMBER'),
    'SUPPORT_SECONDARY_PHONE_NUMBER' => env('SUPPORT_SECONDARY_PHONE_NUMBER'),

    'ALLOW_REGISTER' => env('ALLOW_REGISTER', false),
];
